[workspace]
members = [
    "src/backend_1",
    "src/backend_2",
    "src/manager",
]

[workspace.dependencies]
candid = "^0.9.6"
ic-cdk = "^0.11"
ic-cdk-macros = "^0.8"
ic-cdk-timers = "0.5.0"
ic-stable-structures = "0.5.5"
